export const items = [
  {
    id: "eggplant",
    name: "Салат с хрустящими баклажанами",
    img: "./img-salads/eggplant.jpg",
    alt: "Салат с хрустящими баклажанами",
    to: "/dish",
    kcal: "745",
    gm: "290",
  },
  // {
  //   id: "burata",
  //   name: "Буратта с томатами и печеным перцем",
  //   img: "./img-salads/burata.jpg",
  //   alt: "Буратта",
  //   to: "/dish",
  //   kcal: "745",
  // },
  {
    id: "caesar-shrimps",
    name: "Цезарь с креветками",
    img: "./img-salads/caesar-shrimps.jpg",
    alt: "Цезарь с креветками",
    to: "/dish",
    kcal: "656",
    gm: "230",
  },
  {
    id: "warm-chicken",
    name: "Теплый салат с курицей и копченым сулугуни",
    img: "./img-salads/warm-chicken.jpg",
    alt: "Теплый салат с курицей",
    to: "/dish",
    kcal: "250",
    gm: "245"
  },
  {
    id: "frost-turkey",
    name: "Гриль-салат с индейкой",
    img: "./img-salads/frost.jpg",
    alt: "Гриль-салат с индейкой",
    to: "/dish",
    kcal: "166",
    gm: "246",
  },
  {
    id: "frost-lumb",
    name: "Гриль-салат с ягненком",
    img: "./img-salads/frost.jpg",
    alt: "Гриль-салат с ягненком",
    to: "/dish",
    kcal: "797",
    gm: "246",
  },
  {
    id: "georgian-nuts",
    name: "Овощной салат по-грузински с орехами",
    img: "./img-salads/georgian.jpg",
    alt: "Салат по-грузински",
    to: "/dish",
    kcal: "264",
    gm: "260",
  },
  {
    id: "georgian-spices",
    name: "Овощной салат по-грузински со специями",
    img: "./img-salads/georgian.jpg",
    alt: "Салат по-грузински",
    to: "/dish",
    kcal: "68,5",
    gm: "260",
  },
  {
    id: "greek-salad",
    name: "Греческий салат",
    img: "./img-salads/greek-salad.jpg",
    alt: "Греческий салат",
    to: "/dish",
    kcal: "552",
    gm: "275",
  },
  {
    id: "liver",
    name: "Теплый салат с печенью",
    img: "./img-salads/liver.jpg",
    alt: "Теплый салат с печенью",
    to: "/dish",
    kcal: "418",
    gm: "260",
  },
  {
    id: "olivie-chicken",
    name: "Оливье с ципленком",
    img: "./img-salads/olivie.jpg",
    alt: "Оливье",
    to: "/dish",
    kcal: "462",
    gm: "200",
  },
  {
    id: "olivie-beef",
    name: "Оливье с говядиной",
    img: "./img-salads/olivie.jpg",
    alt: "Оливье",
    to: "/dish",
    kcal: "383",
    gm: "200",
  },
  {
    id: "olivie-sausage",
    name: "Оливье с колбасой",
    img: "./img-salads/olivie.jpg",
    alt: "Оливье",
    to: "/dish",
    kcal: "431",
    gm: "180",
  },
  // {
  //   id: "salmon-salad",
  //   name: "Теплый салат с лососем",
  //   img: "./img-salads/salmon-salad.jpg",
  //   alt: "Теплый салат с лососем",
  //   to: "/dish",
  //   kcal: "745",
  // },
  // {
  //   id: "herring",
  //   name: "Сельдь под шубой",
  //   img: "./img-salads/herring.jpg",
  //   alt: "Сельдь под шубой",
  //   to: "/dish",
  //   kcal: "745",
  // },
  // {
  //   id: "rucala-and-stracitella",
  //   name: "Салат с руколой и страчетеллой",
  //   img: "./img-salads/stracitella.jpg",
  //   alt: "Салат с руколой и страчетеллой",
  //   to: "/dish",
  //   kcal: "745",
  // },
  {
    id: "till",
    name: 'Салат "Тилл"',
    img: "./img-salads/till.jpg",
    alt: "Салат Тилл",
    to: "/dish",
    kcal: "811",
  },
  // {
  //   id: "vegeterian",
  //   name: "Салат вегетарианский",
  //   img: "./img-salads/vegeterian.jpg",
  //   alt: "Салат вегетарианский",
  //   to: "/dish",
  //   kcal: "745",
  // },
  // {
  //   id: "salad-width-avocado",
  //   name: "Салат с авокадо с ореховой заправкой",
  //   img: "./img-salads/width-avocado.jpg",
  //   alt: "Салат с авокадо",
  //   to: "/dish",
  //   kcal: "745",
  // },
  {
    id: "yangiul",
    name: 'Салат «Янгиюль»',
    img: "./img-salads/yangiul.jpg",
    alt: "Салат Янгиюль",
    to: "/dish",
    kcal: "342",
    gm: "230"
  },
];
