export const items = [
  {
    id: "borsch",
    name: "Борщ с чесночными пампушками",
    img: "./img-soups/borsch.jpg",
    alt: "Борщ с чесночными пампушками",
    to: "/dish",
    kcal: "497",
    gm: "340/40/30/60",
  },
  {
    id: "chuchvara",
    name: "Чучвара-шурпа",
    img: "./img-soups/chuchvara.jpg",
    alt: "Чучвара-шурпа",
    to: "/dish",
    kcal: "345",
    gm: "300/2",
  },
  {
    id: "kharcho",
    name: "Харчо с говядиной",
    img: "./img-soups/kharcho.jpg",
    alt: "Харчо с говядиной",
    to: "/dish",
    kcal: "345",
    gm: "350",
  },
  {
    id: "lagman",
    name: "Лагман",
    img: "./img-soups/lagman.jpg",
    alt: "Лагман",
    to: "/dish",
    kcal: "730",
    gm: "340/15/2",
  },
  {
    id: "mushroom-soup",
    name: "Грибной крем-суп",
    img: "./img-soups/mushroom-soup.jpg",
    alt: "Грибной крем-суп",
    to: "/dish",
    kcal: "730",
    gm: "350/40",
  },
  {
    id: "pumpkin",
    name: "Тыквенный крем-суп",
    img: "./img-soups/pumpkin.jpg",
    alt: "Тыквенный крем-суп",
    to: "/dish",
    kcal: "61,4",
    gm: "350",
  },
  {
    id: "shurpa",
    name: "Шурпа",
    img: "./img-soups/shurpa.jpg",
    alt: "Шурпа",
    to: "/dish",
    kcal: "253",
    gm: "320",
  },
  {
    id: "tomyam",
    name: "Том ям с креветками",
    img: "./img-soups/tomyam-shrimp.jpg",
    alt: "Том ям с креветками",
    to: "/dish",
    kcal: "415",
    gm: "340/70",
  },
  {
    id: "uha",
    name: "Карельская уха с форелью и сливками",
    img: "./img-soups/uha.jpg",
    alt: "Карельская уха с форелью и сливками",
    to: "/dish",
    kcal: "358",
    gm: "360",
  },
]